// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ActiveMQService is the renderer's entry point for the operations only
 * ActiveMQ has. Queues and topics, durable subscribers, browsing and sending
 * all go through the canonical services; what is here is the rest.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateDestination declares a queue or a topic.
 */
export function CreateDestination(connID: number, input: $models.ActiveMQDestinationInput): $CancellablePromise<void> {
    return $Call.ByID(2837501373, connID, input);
}

/**
 * MoveMessages drains one destination into another and reports how many the
 * broker moved. The count is the broker's own, which is what separates a move
 * that matched nothing from one that moved everything.
 */
export function MoveMessages(connID: number, input: $models.ActiveMQMoveInput): $CancellablePromise<number> {
    return $Call.ByID(262804722, connID, input);
}

/**
 * PurgeQueue drops everything a destination is holding. There is no undo.
 * 
 * On an Artemis topic this empties every subscription under the address rather
 * than the address itself, which holds nothing - a call against the address
 * would report success and change nothing.
 */
export function PurgeQueue(connID: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(3100897677, connID, name);
}

/**
 * RemoveDestination deletes a destination and everything it holds.
 */
export function RemoveDestination(connID: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(4184532121, connID, name);
}
