// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ActiveMQService is the renderer's entry point for the operations only
 * ActiveMQ has. Queues and topics, durable subscribers, browsing and sending
 * all go through the canonical services; what is here is the rest.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateDestination declares a queue or a topic.
 */
export function CreateDestination(connID: number, input: $models.ActiveMQDestinationInput): $CancellablePromise<void> {
    return $Call.ByID(2837501373, connID, input);
}

/**
 * CreateSubscription registers a durable subscription on a topic.
 */
export function CreateSubscription(connID: number, input: $models.ActiveMQSubscriptionInput): $CancellablePromise<void> {
    return $Call.ByID(1443470090, connID, input);
}

/**
 * DeadLetterQueues finds the destinations dead letters land in, and the
 * destinations that feed them.
 * 
 * The sources are empty on Classic and filled on Artemis, and that is the
 * broker rather than the driver: Artemis records a dead-letter address on
 * every queue, so the topology can be walked backwards; Classic decides by a
 * broker-wide policy and keeps no record of where a dead letter came from.
 */
export function DeadLetterQueues(connID: number): $CancellablePromise<(model$0.DeadLetterQueue | null)[]> {
    return $Call.ByID(1379698213, connID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * MoveMessages drains one destination into another and reports how many the
 * broker moved. The count is the broker's own, which is what separates a move
 * that matched nothing from one that moved everything.
 */
export function MoveMessages(connID: number, input: $models.ActiveMQMoveInput): $CancellablePromise<number> {
    return $Call.ByID(262804722, connID, input);
}

/**
 * Publish sends one or more messages and reports what the broker took.
 */
export function Publish(connID: number, input: $models.ActiveMQPublishInput): $CancellablePromise<model$0.PublishResult | null> {
    return $Call.ByID(303822118, connID, input).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * PurgeQueue drops everything a destination is holding. There is no undo.
 * 
 * On an Artemis topic this empties every subscription under the address rather
 * than the address itself, which holds nothing - a call against the address
 * would report success and change nothing.
 */
export function PurgeQueue(connID: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(3100897677, connID, name);
}

/**
 * RemoveDestination deletes a destination and everything it holds.
 */
export function RemoveDestination(connID: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(4184532121, connID, name);
}

/**
 * RemoveSubscription unsubscribes, discarding whatever it was still owed.
 */
export function RemoveSubscription(connID: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(2685825414, connID, name);
}

/**
 * RetryDeadLetters sends a dead-lettered destination's contents back to the
 * destinations each message originally failed on, and reports how many the
 * broker moved.
 * 
 * The whole destination, because that is the only form either product offers:
 * retryMessages() takes no arguments on Classic or on Artemis.
 */
export function RetryDeadLetters(connID: number, name: string): $CancellablePromise<number> {
    return $Call.ByID(1164999678, connID, name);
}

// Private type creation functions
const $$createType0 = model$0.DeadLetterQueue.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = model$0.PublishResult.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
