// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AzureServiceBusService is the renderer's entry point for the operations only
 * Azure Service Bus has. Listing and describing entities go through the
 * canonical services; what is here is the rest.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelScheduled takes back messages that have not been enqueued yet.
 */
export function CancelScheduled(connID: number, entity: string, sequences: number[]): $CancellablePromise<void> {
    return $Call.ByID(3093429996, connID, entity, sequences);
}

/**
 * CreateEntity declares a queue or a topic in the connection's namespace.
 */
export function CreateEntity(connID: number, input: $models.AzureServiceBusEntityInput): $CancellablePromise<void> {
    return $Call.ByID(2717641736, connID, input);
}

/**
 * CreateRule declares a rule on a subscription.
 */
export function CreateRule(connID: number, input: $models.AzureServiceBusRuleInput): $CancellablePromise<void> {
    return $Call.ByID(2773513569, connID, input);
}

/**
 * CreateSubscription declares a subscription on a topic.
 */
export function CreateSubscription(connID: number, input: $models.AzureServiceBusSubscriptionInput): $CancellablePromise<void> {
    return $Call.ByID(1036100098, connID, input);
}

/**
 * RemoveEntity deletes a queue or a topic, and everything it was holding.
 * A topic takes every subscription on it, and their backlogs with them.
 */
export function RemoveEntity(connID: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(2875084004, connID, name);
}

/**
 * RemoveRule deletes one rule by name.
 * 
 * Deleting the last one leaves a subscription nothing can reach: it stays
 * Active, its backlog stays empty because nothing arrives, and only the
 * subscriptions board's status says so.
 */
export function RemoveRule(connID: number, topic: string, subscription: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(907920453, connID, topic, subscription, name);
}

/**
 * RemoveSubscription deletes a subscription and everything it had not
 * delivered. Those messages were never the topic's to hand out again.
 */
export function RemoveSubscription(connID: number, topic: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(2936189950, connID, topic, name);
}

/**
 * Send publishes to one entity and reports how many the service accepted.
 * 
 * Accepted is not delivered. A queue holds what is sent to it; a topic holds
 * nothing, copying the message into every subscription whose rules let it
 * through and discarding it if none do - and reporting success either way.
 */
export function Send(connID: number, input: $models.AzureServiceBusSendInput): $CancellablePromise<$models.AzureServiceBusSendResult | null> {
    return $Call.ByID(4039833377, connID, input).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UpdateEntity changes an existing entity's settings. Sessions, duplicate
 * detection and partitioning are fixed at creation and are not among them.
 */
export function UpdateEntity(connID: number, input: $models.AzureServiceBusEntityInput): $CancellablePromise<void> {
    return $Call.ByID(3236131605, connID, input);
}

/**
 * UpdateSubscription changes what a subscription lets be changed. The topic
 * and sessions are fixed at creation and are not among them.
 */
export function UpdateSubscription(connID: number, input: $models.AzureServiceBusSubscriptionInput): $CancellablePromise<void> {
    return $Call.ByID(149240795, connID, input);
}

// Private type creation functions
const $$createType0 = $models.AzureServiceBusSendResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
