// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AzureServiceBusService is the renderer's entry point for the operations only
 * Azure Service Bus has. Listing and describing entities go through the
 * canonical services; what is here is the rest.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateEntity declares a queue or a topic in the connection's namespace.
 */
export function CreateEntity(connID: number, input: $models.AzureServiceBusEntityInput): $CancellablePromise<void> {
    return $Call.ByID(2717641736, connID, input);
}

/**
 * RemoveEntity deletes a queue or a topic, and everything it was holding.
 * A topic takes every subscription on it, and their backlogs with them.
 */
export function RemoveEntity(connID: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(2875084004, connID, name);
}

/**
 * UpdateEntity changes an existing entity's settings. Sessions, duplicate
 * detection and partitioning are fixed at creation and are not among them.
 */
export function UpdateEntity(connID: number, input: $models.AzureServiceBusEntityInput): $CancellablePromise<void> {
    return $Call.ByID(3236131605, connID, input);
}
