// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GooglePubSubService is the renderer's entry point for the operations only
 * Google Pub/Sub has. Listing and describing topics go through the canonical
 * services; what is here is the rest.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateTopic declares a topic in the connection's project.
 */
export function CreateTopic(connID: number, input: $models.GooglePubSubTopicInput): $CancellablePromise<void> {
    return $Call.ByID(2501491050, connID, input);
}

/**
 * RemoveTopic deletes a topic. Its subscriptions survive it, pointing at
 * _deleted-topic_ and unable to receive anything ever again.
 */
export function RemoveTopic(connID: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(1496885934, connID, name);
}

/**
 * UpdateTopic changes an existing topic's settings. Labels are replaced
 * wholesale, so a form editing them sends the complete set.
 */
export function UpdateTopic(connID: number, input: $models.GooglePubSubTopicInput): $CancellablePromise<void> {
    return $Call.ByID(3786342201, connID, input);
}
