// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GooglePubSubService is the renderer's entry point for the operations only
 * Google Pub/Sub has. Listing and describing topics go through the canonical
 * services; what is here is the rest.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateSnapshot takes a restore point from one subscription.
 */
export function CreateSnapshot(connID: number, name: string, subscription: string): $CancellablePromise<void> {
    return $Call.ByID(2199453935, connID, name, subscription);
}

/**
 * CreateSubscription declares a subscription on a topic.
 */
export function CreateSubscription(connID: number, input: $models.GooglePubSubSubscriptionInput): $CancellablePromise<void> {
    return $Call.ByID(550444058, connID, input);
}

/**
 * CreateTopic declares a topic in the connection's project.
 */
export function CreateTopic(connID: number, input: $models.GooglePubSubTopicInput): $CancellablePromise<void> {
    return $Call.ByID(2501491050, connID, input);
}

/**
 * DeadLetterQueues finds the topics subscriptions give up into, and which
 * subscriptions point at each of them.
 * 
 * A dead-letter topic in Pub/Sub is an ordinary topic with a subscription's
 * policy aimed at it. Nothing marks one, so this is a walk backwards through
 * the topology - and because the policy belongs to the subscription rather
 * than to the topic, every source names both. A target every one of whose
 * sources sits outside the connection's name prefix is not found, because the
 * walk starts from what the prefix let through.
 */
export function DeadLetterQueues(connID: number): $CancellablePromise<(model$0.DeadLetterQueue | null)[]> {
    return $Call.ByID(123078165, connID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ListSnapshots is every restore point in the project.
 */
export function ListSnapshots(connID: number): $CancellablePromise<$models.GooglePubSubSnapshot[]> {
    return $Call.ByID(3308443124, connID).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * Publish sends to one topic and reports how many the service accepted.
 * 
 * Accepted is not delivered. A topic stores nothing: the publish reaches
 * whatever subscriptions exist at that instant and is discarded if none do,
 * and the service reports success either way.
 */
export function Publish(connID: number, input: $models.GooglePubSubPublishInput): $CancellablePromise<$models.GooglePubSubPublishResult | null> {
    return $Call.ByID(1147653366, connID, input).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * RemoveSnapshot deletes a restore point, and with it the reason the topic was
 * holding everything it could restore.
 */
export function RemoveSnapshot(connID: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(1566444755, connID, name);
}

/**
 * RemoveSubscription deletes a subscription and everything it had not
 * acknowledged. Those messages were never the topic's to hand out again.
 */
export function RemoveSubscription(connID: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(2019229654, connID, name);
}

/**
 * RemoveTopic deletes a topic. Its subscriptions survive it, pointing at
 * _deleted-topic_ and unable to receive anything ever again.
 */
export function RemoveTopic(connID: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(1496885934, connID, name);
}

/**
 * SeekToSnapshot moves a subscription to a restore point.
 * 
 * The other half of Seek - moving to a moment in time - goes through the
 * canonical consumer service, and is degraded against an emulator because the
 * emulator answers it Unimplemented.
 */
export function SeekToSnapshot(connID: number, subscription: string, snapshot: string): $CancellablePromise<void> {
    return $Call.ByID(1746239434, connID, subscription, snapshot);
}

/**
 * UpdateSubscription changes what a subscription lets be changed. The topic,
 * the filter and message ordering are fixed at creation and are not among them.
 */
export function UpdateSubscription(connID: number, input: $models.GooglePubSubSubscriptionInput): $CancellablePromise<void> {
    return $Call.ByID(3224954387, connID, input);
}

/**
 * UpdateTopic changes an existing topic's settings. Labels are replaced
 * wholesale, so a form editing them sends the complete set.
 */
export function UpdateTopic(connID: number, input: $models.GooglePubSubTopicInput): $CancellablePromise<void> {
    return $Call.ByID(3786342201, connID, input);
}

// Private type creation functions
const $$createType0 = model$0.DeadLetterQueue.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.GooglePubSubSnapshot.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.GooglePubSubPublishResult.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
