// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * IBMMQService is the renderer's entry point for the operations only IBM MQ
 * has. Listing and describing queues and topics go through the canonical
 * services; what is here is the rest.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateDestination declares a queue or a topic on the queue manager.
 */
export function CreateDestination(connID: number, input: $models.IBMMQDestinationInput): $CancellablePromise<void> {
    return $Call.ByID(3423170333, connID, input);
}

/**
 * QueueManager is which queue manager this connection speaks to.
 */
export function QueueManager(connID: number): $CancellablePromise<string> {
    return $Call.ByID(159740501, connID);
}

/**
 * RemoveDestination deletes a queue or a topic.
 * 
 * purge decides what happens to a queue that is not empty: without it the
 * queue manager refuses, with it the messages go too and there is no undo.
 * A queue an application has open is refused either way.
 */
export function RemoveDestination(connID: number, name: string, purge: boolean): $CancellablePromise<void> {
    return $Call.ByID(647201913, connID, name, purge);
}
