// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * IBMMQService is the renderer's entry point for the operations only IBM MQ
 * has. Listing and describing queues and topics go through the canonical
 * services; what is here is the rest.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Channels lists every channel definition and what is running on it.
 * 
 * Definitions rather than connections, and the difference is the page: a
 * channel is listed whether or not anything is using it, because it is what
 * decides whether anything may - so a queue manager whose applications are all
 * idle still has rows here, which is exactly when somebody is looking for why
 * they cannot connect.
 */
export function Channels(connID: number): $CancellablePromise<(model$0.Channel | null)[]> {
    return $Call.ByID(3149656599, connID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * CreateDestination declares a queue or a topic on the queue manager.
 */
export function CreateDestination(connID: number, input: $models.IBMMQDestinationInput): $CancellablePromise<void> {
    return $Call.ByID(3423170333, connID, input);
}

/**
 * DeadLetterQueues lists the queues something else dead-letters into.
 * 
 * Found by walking every queue's configuration backwards rather than by
 * looking up a name: nothing marks a dead-letter queue on this family, and
 * what makes one is the queue manager's DEADQ attribute or another queue's
 * backout queue pointing at it.
 */
export function DeadLetterQueues(connID: number): $CancellablePromise<(model$0.DeadLetterQueue | null)[]> {
    return $Call.ByID(2060822981, connID).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * Publish sends to one queue and reports what the queue manager took.
 */
export function Publish(connID: number, input: $models.IBMMQPublishInput): $CancellablePromise<$models.IBMMQPublishResult | null> {
    return $Call.ByID(3409958470, connID, input).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * QueueManager is which queue manager this connection speaks to.
 */
export function QueueManager(connID: number): $CancellablePromise<string> {
    return $Call.ByID(159740501, connID);
}

/**
 * RemoveDestination deletes a queue or a topic.
 * 
 * purge decides what happens to a queue that is not empty: without it the
 * queue manager refuses, with it the messages go too and there is no undo.
 * A queue an application has open is refused either way.
 */
export function RemoveDestination(connID: number, name: string, purge: boolean): $CancellablePromise<void> {
    return $Call.ByID(647201913, connID, name, purge);
}

// Private type creation functions
const $$createType0 = model$0.Channel.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = model$0.DeadLetterQueue.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.IBMMQPublishResult.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
