// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * KinesisService is the renderer's entry point for the operations only Amazon
 * Kinesis has. Listing and describing streams go through the canonical
 * services; what is here is the rest.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateStream declares a stream in the connection's region.
 */
export function CreateStream(connID: number, input: $models.KinesisStreamInput): $CancellablePromise<void> {
    return $Call.ByID(2148805925, connID, input);
}

/**
 * Publish sends to one stream and reports what the service took.
 */
export function Publish(connID: number, input: $models.KinesisPublishInput): $CancellablePromise<$models.KinesisPublishResult | null> {
    return $Call.ByID(1645475376, connID, input).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * RemoveStream deletes a stream and every record in it.
 * 
 * A stream with registered consumers is refused rather than cascaded: an
 * enhanced fan-out consumer is an application somebody stood up, and removing
 * it as a side effect would be a bigger action than the one asked for.
 */
export function RemoveStream(connID: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(3878083365, connID, name);
}

/**
 * Shards lists a stream's shards, open and closed.
 * 
 * Closed ones are included on purpose. A shard split or merged yesterday takes
 * no more writes and still holds every record written to it until retention
 * expires, so leaving it out would hide both those records and the reason the
 * stream reports fewer open shards than the page lists rows.
 */
export function Shards(connID: number, stream: string): $CancellablePromise<(model$0.Shard | null)[]> {
    return $Call.ByID(901783872, connID, stream).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * UpdateStream changes an existing stream's capacity mode, shard count or
 * retention.
 * 
 * Not one call: each of the three is its own asynchronous operation and each
 * is refused while the stream is settling from the last, so this returns when
 * the last of them has been accepted rather than when the stream is done.
 */
export function UpdateStream(connID: number, input: $models.KinesisStreamInput): $CancellablePromise<void> {
    return $Call.ByID(2588592708, connID, input);
}

// Private type creation functions
const $$createType0 = $models.KinesisPublishResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = model$0.Shard.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType3);
