// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NSQService is the renderer's entry point for the operations only NSQ has.
 * Topics, channels and publishing all go through the canonical services; what
 * is here is the rest.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * CreateTopic declares a topic on every nsqd in the connection.
 * 
 * Not TopicService.Create, whose input is a broker address, two queue counts
 * and a permission string - RocketMQ's vocabulary, of which an NSQ topic has
 * none. A name is the whole of what one is.
 */
export function CreateTopic(connID: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(3089113124, connID, name);
}

/**
 * EmptyTopic discards what the topic and every channel under it are holding.
 */
export function EmptyTopic(connID: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(2690610417, connID, name);
}

/**
 * RemoveTopic deletes a topic, its channels and its registration in the
 * discovery tier. There is no undo.
 */
export function RemoveTopic(connID: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(2147916580, connID, name);
}

/**
 * SetTopicPaused stops or resumes delivery into a topic's channels.
 * 
 * A boolean rather than two methods, because it is one control with two
 * positions and the page reads the current state back off the topic listing.
 */
export function SetTopicPaused(connID: number, name: string, paused: boolean): $CancellablePromise<void> {
    return $Call.ByID(876836892, connID, name, paused);
}
