// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NSQService is the renderer's entry point for the operations only NSQ has.
 * Topics, channels and publishing all go through the canonical services; what
 * is here is the rest.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateChannel declares a channel on every nsqd carrying its topic.
 * 
 * It starts empty whatever the topic already holds: nsqd copies a message into
 * the channels that exist when it arrives, so there is nothing for a new one
 * to catch up on and no position to start it from.
 */
export function CreateChannel(connID: number, input: $models.NSQChannelInput): $CancellablePromise<void> {
    return $Call.ByID(960771588, connID, input);
}

/**
 * CreateTopic declares a topic on every nsqd in the connection.
 * 
 * Not TopicService.Create, whose input is a broker address, two queue counts
 * and a permission string - RocketMQ's vocabulary, of which an NSQ topic has
 * none. A name is the whole of what one is.
 */
export function CreateTopic(connID: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(3089113124, connID, name);
}

/**
 * EmptyChannel discards one channel's backlog and leaves the rest of the topic
 * alone, which is what separates it from emptying the topic.
 */
export function EmptyChannel(connID: number, input: $models.NSQChannelInput): $CancellablePromise<void> {
    return $Call.ByID(3517095425, connID, input);
}

/**
 * EmptyTopic discards what the topic and every channel under it are holding.
 */
export function EmptyTopic(connID: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(2690610417, connID, name);
}

/**
 * RemoveChannel deletes a channel and its backlog, in the discovery tier as
 * well as on every nsqd. There is no undo.
 */
export function RemoveChannel(connID: number, input: $models.NSQChannelInput): $CancellablePromise<void> {
    return $Call.ByID(57321732, connID, input);
}

/**
 * RemoveTopic deletes a topic, its channels and its registration in the
 * discovery tier. There is no undo.
 */
export function RemoveTopic(connID: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(2147916580, connID, name);
}

/**
 * SetChannelPaused stops or resumes delivery to one channel's consumers. The
 * other channels under the topic keep running.
 */
export function SetChannelPaused(connID: number, input: $models.NSQChannelInput, paused: boolean): $CancellablePromise<void> {
    return $Call.ByID(170130160, connID, input, paused);
}

/**
 * SetTopicPaused stops or resumes delivery into a topic's channels.
 * 
 * A boolean rather than two methods, because it is one control with two
 * positions and the page reads the current state back off the topic listing.
 */
export function SetTopicPaused(connID: number, name: string, paused: boolean): $CancellablePromise<void> {
    return $Call.ByID(876836892, connID, name, paused);
}
