// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NSQService is the renderer's entry point for the operations only NSQ has.
 * Topics, channels and publishing all go through the canonical services; what
 * is here is the rest.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Connections lists every consumer holding a subscription open on the cluster.
 * 
 * Consumers only. A client appears in the stats of the channel it subscribed
 * to and nowhere else, so a connection that has not subscribed yet and a
 * producer are both absent - which is why the page is titled for what it
 * shows rather than for every socket the daemons hold.
 */
export function Connections(connID: number): $CancellablePromise<(model$0.ClientConnection | null)[]> {
    return $Call.ByID(734404310, connID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * CreateChannel declares a channel on every nsqd carrying its topic.
 * 
 * There is no position to start it from. What it gets is whatever nsqd is
 * still holding: nothing, on a topic that already has a channel, and the
 * topic's own queue on one that had none to copy into.
 */
export function CreateChannel(connID: number, input: $models.NSQChannelInput): $CancellablePromise<void> {
    return $Call.ByID(960771588, connID, input);
}

/**
 * CreateTopic declares a topic on every nsqd in the connection.
 * 
 * Not TopicService.Create, whose input is a broker address, two queue counts
 * and a permission string - RocketMQ's vocabulary, of which an NSQ topic has
 * none. A name is the whole of what one is.
 */
export function CreateTopic(connID: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(3089113124, connID, name);
}

/**
 * EmptyChannel discards one channel's backlog and leaves the rest of the topic
 * alone, which is what separates it from emptying the topic.
 */
export function EmptyChannel(connID: number, input: $models.NSQChannelInput): $CancellablePromise<void> {
    return $Call.ByID(3517095425, connID, input);
}

/**
 * EmptyTopic discards what the topic and every channel under it are holding.
 */
export function EmptyTopic(connID: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(2690610417, connID, name);
}

/**
 * Nodes lists the daemons the send console can address.
 */
export function Nodes(connID: number): $CancellablePromise<string[]> {
    return $Call.ByID(3925263922, connID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Publish sends through one nsqd and reports which one took the messages.
 */
export function Publish(connID: number, input: $models.NSQPublishInput): $CancellablePromise<$models.NSQPublishResult | null> {
    return $Call.ByID(3159053456, connID, input).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * RemoveChannel deletes a channel and its backlog, in the discovery tier as
 * well as on every nsqd. There is no undo.
 */
export function RemoveChannel(connID: number, input: $models.NSQChannelInput): $CancellablePromise<void> {
    return $Call.ByID(57321732, connID, input);
}

/**
 * RemoveTopic deletes a topic, its channels and its registration in the
 * discovery tier. There is no undo.
 */
export function RemoveTopic(connID: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(2147916580, connID, name);
}

/**
 * SetChannelPaused stops or resumes delivery to one channel's consumers. The
 * other channels under the topic keep running.
 */
export function SetChannelPaused(connID: number, input: $models.NSQChannelInput, paused: boolean): $CancellablePromise<void> {
    return $Call.ByID(170130160, connID, input, paused);
}

/**
 * SetTopicPaused stops or resumes delivery into a topic's channels.
 * 
 * A boolean rather than two methods, because it is one control with two
 * positions and the page reads the current state back off the topic listing.
 */
export function SetTopicPaused(connID: number, name: string, paused: boolean): $CancellablePromise<void> {
    return $Call.ByID(876836892, connID, name, paused);
}

// Private type creation functions
const $$createType0 = model$0.ClientConnection.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = $models.NSQPublishResult.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
