// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SolaceService is the renderer's entry point for the operations only Solace
 * has. Listing and describing queues go through the canonical services; what
 * is here is the rest.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateQueue declares a queue in this connection's Message VPN.
 */
export function CreateQueue(connID: number, input: $models.SolaceQueueInput): $CancellablePromise<void> {
    return $Call.ByID(2606363973, connID, input);
}

/**
 * CreateTopicEndpoint declares an endpoint whose name is its subscription.
 * 
 * No other field: a topic endpoint has no exchange type and nothing to decide
 * beyond the topic it is called after.
 */
export function CreateTopicEndpoint(connID: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(3424093948, connID, name);
}

/**
 * DeadMsgQueues lists the queues something else dead-letters into.
 * 
 * Found by walking every endpoint's configuration backwards rather than by
 * looking up a name: nothing marks a dead message queue on this family, and
 * what makes one is another queue's or topic endpoint's pointer. A target with
 * no depth is one the Message VPN does not hold - which is the ordinary state
 * of the pointer every endpoint ships with, and what makes a message given up
 * on disappear rather than move.
 */
export function DeadMsgQueues(connID: number): $CancellablePromise<(model$0.DeadLetterQueue | null)[]> {
    return $Call.ByID(2394503593, connID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * MsgVPN is which Message VPN this connection reads.
 */
export function MsgVPN(connID: number): $CancellablePromise<string> {
    return $Call.ByID(2460681033, connID);
}

/**
 * Publish sends to one queue or one topic and reports what the broker took.
 */
export function Publish(connID: number, input: $models.SolacePublishInput): $CancellablePromise<$models.SolacePublishResult | null> {
    return $Call.ByID(2722482709, connID, input).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * RemoveQueue deletes a queue and whatever it was holding.
 * 
 * No purge flag: SEMP has no precondition to ask for, and it deletes a full
 * queue as readily as an empty one. The confirmation on the board says so
 * rather than this offering a guard the broker does not have.
 */
export function RemoveQueue(connID: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(2355590309, connID, name);
}

/**
 * RemoveTopicEndpoint deletes one, and whatever it was holding.
 */
export function RemoveTopicEndpoint(connID: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(2965833628, connID, name);
}

/**
 * Subscribe adds a topic subscription to a queue.
 * 
 * Two arguments rather than a binding, because there is no exchange between a
 * topic and a queue here: the source, the routing key and the handle are all
 * the one topic string.
 * 
 * Nothing already spooled moves. A subscription added now attracts what is
 * published from now on.
 */
export function Subscribe(connID: number, queue: string, topic: string): $CancellablePromise<void> {
    return $Call.ByID(2879240922, connID, queue, topic);
}

/**
 * Unsubscribe drops a topic subscription from a queue. What it already brought
 * stays where it is.
 */
export function Unsubscribe(connID: number, queue: string, topic: string): $CancellablePromise<void> {
    return $Call.ByID(2611046851, connID, queue, topic);
}

// Private type creation functions
const $$createType0 = model$0.DeadLetterQueue.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.SolacePublishResult.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
