// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SolaceService is the renderer's entry point for the operations only Solace
 * has. Listing and describing queues go through the canonical services; what
 * is here is the rest.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateQueue declares a queue in this connection's Message VPN.
 */
export function CreateQueue(connID: number, input: $models.SolaceQueueInput): $CancellablePromise<void> {
    return $Call.ByID(2606363973, connID, input);
}

/**
 * MsgVPN is which Message VPN this connection reads.
 */
export function MsgVPN(connID: number): $CancellablePromise<string> {
    return $Call.ByID(2460681033, connID);
}

/**
 * RemoveQueue deletes a queue and whatever it was holding.
 * 
 * No purge flag: SEMP has no precondition to ask for, and it deletes a full
 * queue as readily as an empty one. The confirmation on the board says so
 * rather than this offering a guard the broker does not have.
 */
export function RemoveQueue(connID: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(2355590309, connID, name);
}
