// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SQSService is the renderer's entry point for the operations only Amazon SQS
 * has. Listing and describing queues go through the canonical services; what
 * is here is the rest.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateQueue declares a queue in the connection's region.
 */
export function CreateQueue(connID: number, input: $models.SQSQueueInput): $CancellablePromise<void> {
    return $Call.ByID(2018066557, connID, input);
}

/**
 * Publish sends to one queue and reports how many the service accepted.
 */
export function Publish(connID: number, input: $models.SQSPublishInput): $CancellablePromise<$models.SQSPublishResult | null> {
    return $Call.ByID(2574354685, connID, input).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * PurgeQueue discards everything the queue holds.
 * 
 * The call returning is not the queue being empty: SQS purges asynchronously,
 * may also delete anything sent in the following minute, and may keep
 * delivering what was sent before it for about as long.
 */
export function PurgeQueue(connID: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(3550643484, connID, name);
}

/**
 * RemoveQueue deletes a queue and everything in it. There is no undo, and SQS
 * refuses the name for 60 seconds afterwards.
 */
export function RemoveQueue(connID: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(2204450429, connID, name);
}

/**
 * UpdateQueue changes an existing queue's settings. Whether a queue is FIFO is
 * not among them: that is fixed at creation and spelled in its name.
 */
export function UpdateQueue(connID: number, input: $models.SQSQueueInput): $CancellablePromise<void> {
    return $Call.ByID(784278494, connID, input);
}

// Private type creation functions
const $$createType0 = $models.SQSPublishResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
